//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eai.Cds.Poc.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsightLink
    {
        public int InsightLinkId { get; set; }
        public int InsightId { get; set; }
        public string LinkLabel { get; set; }
        public string LinkUrl { get; set; }
        public string Vv_LinkType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    
        public virtual Insight Insight { get; set; }
        public virtual VV_InsightLink VV_InsightLink { get; set; }
    }
}
