Declare @CreateUser as nvarchar(50)
set @CreateUser = 'initialLoad'

declare @labelAbsolute as nvarchar(25)
declare @labelSmart as nvarchar(25)

set @labelAbsolute = 'absolute';
set @labelSmart = 'smart';

declare @insightId as int;

INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])
VALUES('Protect yourself and the ones you love.', 'Getting a shot is the best way to keep from getting the flu and giving it to others. Get a flu shot before the season starts.', 'Flu shot reminder for adults', 'NOT FOR PROVIDER MESSAGING', 0, 'WLP_Influenza vaccine_Reminder	', getdate(), @CreateUser)

	set @insightId = @@identity;
	INSERT INTO [dbo].[InsightLink]([InsightId], [LinkLabel], [LinkUrl], [Vv_LinkType], [CreateDate], [CreateUser])
	VALUES(@insightId, 'Link to Amazon', 'http://www.amazon.com', @labelAbsolute, getdate(), @CreateUser)

	
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Make yourself a flu fighter.', 'Getting a shot is the best way to protect yourself and others from the flu. Get your free flu shot today.', 'Flu shot reminder for adults', 'NOT FOR PROVIDER MESSAGING.', 0, 'WLP_Influenza vaccine_Reminder_Purdue	', getdate(), @CreateUser)

	set @insightId = @@identity;
	INSERT INTO [dbo].[InsightLink]([InsightId], [LinkLabel], [LinkUrl], [Vv_LinkType], [CreateDate], [CreateUser])
	VALUES(@insightId, 'Link to Smart App', 'http://localhost:4200/launch', @labelSmart, getdate(), @CreateUser)

INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Have you completed your MyHealth Assessment?', 'Your answers will help us give you personalized information about programs and services that can help you be healthier. Go to Anthem.com to complete your survey today.', 'HRA completion reminder', 'Not for provider messaging.', 0, 'WLN_Wellness_HRA completion	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Know the signs of depression.', 'People with depression can have changes in sleeping and eating, or have trouble concentrating or doing everyday tasks. See your provider if you have depression symptoms that last more than 2 weeks. Depression can be treated! Call your doctor to ask about it.', 'Signs of depression info', 'NOT FOR PROVIDER MESSAGING.', 1, 'MCD_INF_Depression_signs_01	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Ask your doctor about a tetanus shot.', 'People need to have a tetanus shot every 10 years. This shot protects against an infection some people call lockjaw that can cause painful spasms in your jaw, chest, neck, back and stomach muscles. Ask your doctor if you are up to date on your tetanus shot.', 'Tetanus vaccine', 'Not for provider messaging.', 0, 'WLN_Wellness_Tetanus vaccine	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Protect yourself and the ones you love.', 'Getting a shot is the best way to keep from getting the flu and giving it to others. Get a flu shot before the season starts.', 'Influenza vaccine', 'Not for provider messaging.', 0, 'WLN_Wellness_Influenza vaccine	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Ask your doctor if you are getting enough calcium.', 'Calcium keeps your bones strong and healthy. Since you are 25 to 50 years old, the North American Menopause Society recommends at least 1,000 mg of calcium each day. You can get calcium by eating or drinking 3 to 4 cups of dairy products. You can also get it from leafy green vegetables, soy and tofu, nuts and calcium-fortified foods. If you haven''t yet talked to your doctor, ask if you are getting enough calcium or if you need to take a daily supplement.', 'Calcium Intake Advisory (Women ages 25-50)', 'Not for Provider Messaging', 0, 'WLP_Women 25-50_1000mg calcium	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Three things to ask your doctor.', 'Next time you talk to your doctor, ask about <li>Your well-woman visit</li><li>A Pap test</li><li>A flu shot and other shots</li>', 'Wellness age 26-39 women', 'NOT FOR PROVIDER MESSAGING.', 0, 'WLP_Wellness_Age 26-39 Women	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Go online to learn about food serving sizes.', 'How much should you eat each day? Ask your provider for a copy of the latest food guide, or get one at www.health.gov/dietaryguidelines. The US Department of Health and Human Services suggests: <li> 2-and-a-half cups of fruits and vegetables </li><li>3 ounces or more of whole grains</li><li>3 cups of non-fat or low-fat dairy</li>', 'Nutrition and recommended portions tips', 'NOT FOR PROVIDER MESSAGING.', 0, 'MCD_INF_Nutrition_portion size_01	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Develop healthy sleep habits.', 'Do you have trouble getting enough sleep? These tips may help: </li><li>Go to bed at the same time </li><li>Create a relaxing bedtime routine </li><li>Do not work or watch TV in your bedroom </li><li>Eat heavy meals and exercise earlier in the day</li>', 'Sleep Disorders - Healthy Sleep Habits', 'NOT FOR PROVIDER MESSAGING', 1, 'MCD_INF_Sleep Tips_01	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Exercise regularly to stay healthy.', 'Exercise can help you stay healthy. Here are some tips to get more exercise: <li>Start slowly, and work your way up </li><li>Walk regularly, working up to a half hour a few times a week </li><li>Start making the walk harder or longer. </li><li>Have fun! Join clubs, dance, swim or find something you enjoy</li>', 'Fitness tips', 'Not for Provider Messaging', 0, 'MCD_INF_Fitness Tips_01	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('One less thing to remember.', 'Want to make your life a little easier? Then sign up to have your prescriptions refilled automatically at your Kroger Co. pharmacy store. Just go to https://autorefill.reportsonline.com/ar/Kroger/. We''ll refill your prescriptions and send you a text or email, or give you a call, when they''re ready. It''s just that simple.', 'Personal Health Advocate info', 'NOT FOR PROVIDER MESSAGING', 0, 'KRO_INF_Personal Health Advocate	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Remember Slip, Slop, and Slap! when you are in the sun.', 'Sunburn and sun exposure can increase the risk of skin cancer. Follow the American Cancer Society''s advice: Slip, Slop, and Slap. Slip on a shirt. Slop on sunscreen. Slap on a hat. Serious sunburn symptoms include fever, chills, upset stomach and confusion. If you have these symptoms, see your doctor. Enjoy your time outdoors this summer and remember, Slip, Slop, and Slap!', 'Wellness protection from sun exposure', 'NOT FOR PROVIDER MESSAGING.', 0, 'MCD_INF_Sun Exposure	', getdate(), @CreateUser)
INSERT INTO [dbo].[Insight]([MemberMessageHeadline], [MemberMessage],[ProviderMessageheadline], [MessageType], [Sensitiveind], [RuleNameFriendly],[CreateDate],[CreateUser])VALUES('Time to see your doctor.', 'If you have not seen a doctor recently, schedule your annual wellness visit soon.', 'Annual Wellness Visit Almost Gap', 'NOT FOR PROVIDER MESSAGING.', 0, 'WLP_Annual Wellness Visit_Almost Gap	', getdate(), @CreateUser)

GO